INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES (USER_SEQUENCE.NEXTVAL, 'xtremax',
'$2a$10$9/44Rne7kQqPXa0cY6NfG.3XzScMrCxFYjapoLq/wFmHz7EC9praK');

INSERT INTO ROLE(ID, CODE, LABEL) VALUES (1, 'ROLE_USER', 'USER');
INSERT INTO ROLE(ID, CODE, LABEL) VALUES (2, 'ROLE_ADMIN', 'ADMIN');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) SELECT u.ID, r.ID FROM USER u, ROLE r WHERE u.username = 'xtremax' AND r.ID = 1;
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) SELECT u.ID, r.ID FROM USER u, ROLE r WHERE u.username = 'xtremax' AND r.ID = 2;