CREATE TABLE ROLE (
    ID NUMBER(38) NOT NULL PRIMARY KEY,
    CODE VARCHAR(50) NOT NULL,
    LABEL VARCHAR(50) NOT NULL
);

CREATE TABLE USER (
    ID NUMBER(38) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE SEQUENCE USER_SEQUENCE START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE TABLE USER_ROLE (
    USER_ID NUMBER(38) NOT NULL,
    ROLE_ID NUMBER(38) NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    CONSTRAINT FK_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);